#! /usr/bin/env bash
#
# Install build dependencies.
#
# This is made to work in the Docker container used with CircleCI
# (see .circleci/config.yaml). It may or not work elsewhere.
#
set -eu

# Strict requirements for the build
go mod init mjambon.com/vanity
go get gopkg.in/yaml.v3
go get github.com/jessevdk/go-flags

# Optional. Needed to build examples/
sudo apt-get update
sudo apt-get install graphviz -y
